flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- byteable-0.1.1
- cereal-0.5.4.0
- connection-0.2.6
- cryptonite-0.21
- data-default-class-0.1.2.0
- dlist-0.8.0.2
- foundation-0.0.3
- hashable-1.2.5.0
- hflags-0.4.2
- hourglass-0.2.10
- integer-logarithms-1
- memory-0.14
- mtl-2.2.1
- network-2.6.3.1
- pem-0.2.2
- primitive-0.6.2.0
- random-1.1
- scientific-0.3.4.10
- socks-0.5.5
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- tls-1.3.9
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.2
- uuid-types-1.0.3
- vector-0.12.0.0
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
resolver: ghc-8.0.1
